apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: demo-voting-app
  template:
    metadata:
    name: postgres-pod
    labels:
      name: postgres-pod
      app: demo-voting-app
  spec:
    containers:
      - 
        name: postgre
        image: postgres:9.4
        env:
          - name: "POSTGRES_PASSWORD"
            value: "password"
        ports:
          - containerPort: 5432

